// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGabjNVSSJFLrepdgRlWfjextz6QidKY',
    appId: '1:184127431754:web:7f6bb3cca1b268c8dbf2b3',
    messagingSenderId: '184127431754',
    projectId: 'ajay-try',
    authDomain: 'ajay-try.firebaseapp.com',
    storageBucket: 'ajay-try.appspot.com',
    measurementId: 'G-PZLXH7C0LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBslbArKObi_IJ4R3bZ-2XhT36cbr1KIho',
    appId: '1:184127431754:android:d1475780130de8c4dbf2b3',
    messagingSenderId: '184127431754',
    projectId: 'ajay-try',
    storageBucket: 'ajay-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUjc9Dw4p0jPPoi5XcWWD8Z67fLPPNlLM',
    appId: '1:184127431754:ios:6681f458f2c8f61cdbf2b3',
    messagingSenderId: '184127431754',
    projectId: 'ajay-try',
    storageBucket: 'ajay-try.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUjc9Dw4p0jPPoi5XcWWD8Z67fLPPNlLM',
    appId: '1:184127431754:ios:6681f458f2c8f61cdbf2b3',
    messagingSenderId: '184127431754',
    projectId: 'ajay-try',
    storageBucket: 'ajay-try.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpGabjNVSSJFLrepdgRlWfjextz6QidKY',
    appId: '1:184127431754:web:5f45115fae9d4c81dbf2b3',
    messagingSenderId: '184127431754',
    projectId: 'ajay-try',
    authDomain: 'ajay-try.firebaseapp.com',
    storageBucket: 'ajay-try.appspot.com',
    measurementId: 'G-6FPK653FNV',
  );
}
